### ISSUE TITLE
What this sub task mean ?

### ISSUE THREAD

**Issue by VanillaTiger** [mcv-m6-video/class2022#1]
![image](https://user-images.githubusercontent.com/24492652/157766550-c25740b7-c9fd-4a8b-9431-92a0d538f042.png)

Should we use some pretrained models on Kitti to detect using detectron2 fastrcnn, yolo3 and ssd512 I do not see anything provided in the materials of the project?

Also in the results_optical_flow_kitti folder there are just 2 green images, should it be like that? is something missing ?

**Comment by jrhupc** [comment]
> Should we use some pretrained models on Kitti to detect using detectron2 fastrcnn, yolo3 and ssd512 I do not see anything provided in the materials of the project?

I guess you are referring to AI City dataset (not Kitti). No, you do not need to run any detectors (for this week). The detector outputs are already provided in the AICIty_data on the virtual campus. Please check the _**Readme.txt**_ file in the **_info_** folder

> Also in the results_optical_flow_kitti folder there are just 2 green images, should it be like that? is something missing ?

Again, check the readme of the Kitti dataset. In this case go to the Kitti webpage (link in the slides) and download the optical flow development kit (you need to register to do that but it is a semi-automatic process and usually done in just 10min). You can obtain the original images and ground truth for that. Just a hint from the kitti info:

```
Optical flow maps are saved as 3-channel uint16 PNG images: The first channel
contains the u-component, the second channel the v-component and the third
channel denotes if a valid ground truth optical flow value exists for that
pixel (1 if true, 0 otherwise). To convert the u-/v-flow into floating point
values, convert the value to float, subtract 2^15 and divide the result by 64:
```
